---
# BOSH Director must have Cloud Config with the following properties:
# - vm_type: tiny
# - network: manual

name: echo_deployment

director_uuid: 28539132-6d43-4e1b-bf40-f2ce032ee9f8

releases:
- name: echo_release
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: echo_ig
  instances: 1
  vm_type: tiny
  stemcell: ubuntu
  networks:
  - name: manual
  jobs:
  - name: echo_job
    release: echo_release

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
