---
# BOSH Director must have Cloud Config with the following properties:
# - vm_type: tiny
# - network: manual

name: echo_deployment

director_uuid: 93c01d2d-a2a5-49d8-8d02-389fd223a9cf

releases:
- name: echo-bosh-example-release
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: echo_ig
  instances: 1
  vm_type: tiny
  stemcell: ubuntu
  networks:
  - name: manual
  jobs:
  - name: echo_job
    release: echo-bosh-example-release

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
