---
# BOSH Director must have Cloud Config with the following properties:
# - vm_type: tiny
# - network: manual

name: echo_deployment

director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
- name: echo_release
  version: latest

stemcells:
- alias: ubuntu
  os: bosh-warden-boshlite-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: echo_ig
  instances: 1
  vm_type: small
  stemcell: ubuntu
  provides:
    FIXME: FIXME
  networks:
  - name: manual
    # static_ips:
    #   - 10.244.0.42
  jobs:
  - name: echo_job
    release: echo_release
- name: echo_ig_2
  instances: 1
  vm_type: small
  stemcell: ubuntu
  networks:
  - name: manual
    # static_ips:
    #   - 10.244.0.42
  jobs:
  - name: echo_job
    release: echo_release
    consumes:
      other_guy:
        from: echo_ig

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
